main:
  listen : 0.0.0.0:8080
  dispatchers : 20
  serveruser : admin
  serverpass : 261a5983599fd57a016122ec85599ec4
  dangerzone : yes
  readonly : no
  authread : no
  authwrite : yes
  radoconns : 25
  logfile : no
  logpath: /opt/webrados.log
  allpools: no
  poollist:
    - bublics
    - donuts
    - images
  usersfile: users.txt
  authtype: apikey # apikey , basic, jwt, none
cache:
  shards: 1024
  lifewindow: 10
  cleanwindow: 1
  maxrntriesinwindow: 600000
  maxentrysize: 5000
  maxcachemb: 1024
monitoring:
  enabled : yes
  url:  127.0.0.1:9090
  user: admin
  pass: admin
